---
title: "Kingfisher results"
author: "JL Villanueva"
date: "5/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(dplyr)
library(knitr)
library(readr)
library(kableExtra)

raw_data <- read_delim("~/Documents/2020_05_05_RUN_PROVA3_Presence%20Absence%20Result.csv", ",", escape_double = FALSE, trim_ws = TRUE, skip = 20)

raw_data$pos<-raw_data$Well

table1 <- raw_data %>%
  select(`Well Position`, Sample,Target,Cq, pos) %>%
  spread(key=Target, value=Cq) %>%
  mutate(Sample=ifelse(nchar(Sample)>3,substr(Sample, 4, 12),Sample)) %>%
  mutate(pos=ifelse(Sample=='PC', 0, pos)) %>%
  arrange(pos) %>%
  select(-pos)

#Reorder columns
table1 <- table1[, c(2, 1, 4, 5, 6, 3)]

#Count number of genes not undetermined
table1$pos_targets = rowSums(table1[,c('N gene','ORF1ab','S gene')] != 'Undetermined')

table1 <- table1 %>% 
  mutate(interpretation = case_when(    
    Sample=='PC' ~ 'control',
    Sample=='NC' ~ 'control',
    MS2=='Undetermined' ~ 'No válido',
    pos_targets >=2 ~ 'Positivo',
    MS2!='Undetermined' && pos_targets == 0 ~ 'Indetectable',

    TRUE ~ 'revisar'
  ))

summary_table <- table(table1[table1$interpretation != 'control',]$interpretation, pos_targets = table1[table1$interpretation != 'control',]$pos_targets)

```

## Introducción
Texto de ejemplo. Podemos poner una breve descripción.

## Summary
Resumen de interpretación según número de targets positivos
```{r tables, echo=FALSE}
kable(summary_table)
```

## Tabla resultados
```{r tables2, echo=FALSE}
kable(table1,digits=2) %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```


